adding publish commad before deployment
got past the pipeline deployment error 
Job Job1: Step input azureSubscription references service connection ConnectDevOpsWow86c7 which could not be found. The service connection does not exist or has not been authorized for use. For authorization details, refer to https://aka.ms/yamlauthz.

which was a known 
issue https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=vsts#troubleshooting-authorization-for-a-yaml-pipeline

Looks like deploy is now failing because of 
Error: No package found with specified pattern: D:\a\1\a\**\*.zip